/**
 * Regenerates an asset manifest and a fact sheet for every registered script.
 *
 * Run with `npm run docs`. The markdown is generated — edit `src/data/*.ts`,
 * never the files this writes.
 */
import {writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {SCRIPTS, docNames} from '../src/data/scripts';
import {buildFactSheet, buildManifest} from '../src/assets/manifest';
import {totalFrames} from '../src/reel/timing';
import type {ReelScript} from '../src/data/types';

// npm scripts run from the package root.
const root = process.cwd();
const esc = (s: string) => s.replace(/\|/g, '\\|');

const assetsDoc = (script: ReelScript) => {
  const rows = buildManifest(script);
  const missing = rows.filter((r) => r.status === 'PLACEHOLDER');

  return `# Asset manifest — ${script.subject}

> Generated by \`npm run docs\`. Do not edit by hand — edit the script in \`src/data/\`.

**${script.width}×${script.height} · ${script.fps}fps · ${script.durationInSeconds}s (${totalFrames(script)} frames)**

${missing.length} of ${rows.length} slots are still placeholders. Drop the licensed
file at the target path under \`public/\`, then set that scene's \`src\` in
the script data to the same path. Nothing else needs changing —
\`AssetSlot\` swaps the placeholder for the real file automatically.

## Slots

| # | Asset ID | Type | Goes at | Out | Dur | Scene | Drop the file here | Status |
|---|---|---|---|---|---|---|---|---|
${rows
  .map(
    (r, i) =>
      `| ${i + 1} | \`${r.assetId}\` | ${r.kind} | ${r.inPoint} | ${r.outPoint} | ${r.durationSeconds}s | \`${r.sceneId}\` (${r.sceneType}) | \`public/${r.targetPath}\` | ${r.status} |`,
  )
  .join('\n')}

## Briefs and rights

${rows
  .map(
    (r) => `### \`${r.assetId}\` → \`public/${r.targetPath}\`
- **Lands at** ${r.inPoint}–${r.outPoint} (${r.durationSeconds}s), scene \`${r.sceneId}\`
- **Should show:** ${esc(r.brief)}
- **Rights:** ${esc(r.sourceNote)}`,
  )
  .join('\n\n')}

## Clearance rules

This is an unofficial, fan-made editorial video. Before publishing:

1. **No commercial music.** The \`audio-music\` slot must be a licensed
   production track. Do not use any 50 Cent recording, or any commercially
   released song, without a synchronisation licence.
2. **No broadcast, film or music-video footage**, including \`Power\`,
   \`Get Rich or Die Tryin'\` (the film), Super Bowl coverage and award shows.
3. **No album artwork, logos or wordmarks** — not G-Unit, not Shady/Aftermath,
   not Starz, not vitaminwater, not the NFL.
4. **Stills must be licensed** (Getty/AP/Shutterstock editorial or equivalent).
   A press photo found via search is not licensed.
5. Keep the on-screen disclaimer in the end card and repeat it in the
   Instagram caption.
`;
};

const factsDoc = (script: ReelScript) => {
  const rows = buildFactSheet(script);
  const toVerify = rows.filter((r) => r.needsVerification);

  return `# Fact sheet — ${script.subject}

> Generated by \`npm run docs\`. Do not edit by hand — edit the script in \`src/data/\`.

Every factual claim the reel puts on screen, with the source recorded in the
script data. Nothing here was invented for the edit; anything that could not be
pinned to a specific citation is flagged **VERIFY** and must be confirmed
against a named outlet — or cut — before publishing.

## Claims

| At | Scene | Claim | Source | Verify |
|---|---|---|---|---|
${rows
  .map(
    (r) =>
      `| ${r.inPoint} | \`${r.sceneId}\` | ${esc(r.claim)} | ${esc(r.source)} | ${r.needsVerification ? '**VERIFY**' : '—' } |`,
  )
  .join('\n')}

## Open items (${toVerify.length})

${
  toVerify.length === 0
    ? 'None.'
    : toVerify
        .map((r) => `- [ ] **${r.inPoint} \`${r.sceneId}\`** — ${esc(r.claim)}\n      ${esc(r.source)}`)
        .join('\n')
}

## What the reel deliberately does not claim

- No dollar figure for anyone's personal payout.
- No motive, no attribution of blame, and no detail about the 2000 shooting
  beyond that it happened and was survived.
- No quotes. The \`quote\` card exists in the component library but is unused
  here, because a quote is a claim about what someone said and needs its own
  citation.
- No sales or certification figures beyond published chart positions.
`;
};

SCRIPTS.forEach((script, i) => {
  const names = docNames(script, i);
  writeFileSync(join(root, names.assets), assetsDoc(script));
  writeFileSync(join(root, names.facts), factsDoc(script));

  const frames = totalFrames(script);
  const beats = script.scenes.map((s) => s.durationInFrames / script.fps);
  const avg = beats.reduce((a, b) => a + b, 0) / beats.length;

  console.log(`${names.assets} + ${names.facts} written.`);
  console.log(
    `  ${script.id}: ${script.scenes.length} scenes · ${frames} frames · ` +
      `${(frames / script.fps).toFixed(2)}s · avg beat ${avg.toFixed(2)}s ` +
      `(min ${Math.min(...beats).toFixed(2)}s, max ${Math.max(...beats).toFixed(2)}s)`,
  );
});
